apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { - include "myapp.name" . - } }
  namespace: { { - include "myapp.namespace" . - } }
  labels:
    app: { { - include "myapp.name" . - } }
spec:
  replicas: { { - .Values.replicaCount - } }
  selector:
    matchLabels:
      app: { { - include "myapp.name" . - } }
  template:
    metadata:
      labels:
        app: { { - include "myapp.name" . - } }
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: { { - include "myapp.name" . - } }
          image: "{{- .Values.image.repository -}}:{{- .Values.image.tag -}}"
          imagePullPolicy: { { - .Values.image.pullPolicy - } }
          ports:
            - containerPort: { { .Values.service.targetPort } }
          resources: { { - toYaml .Values.resources | nindent 12 } }
