replicaCount: 1

image:
  repository: 192.168.80.100:5000/network-test
  tag: v1.0.35
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  limits:
    cpu: "1"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

nodeSelector: {}

tolerations: []

affinity: {}
